export const CARS = [
  {
    id: 'brio',
    name: 'Honda Brio',
    type: 'Compact, City-friendly',
    capacity: '5 Kursi',
    transmission: 'Automatic/Manual',
    lepasKunci: true,
    price: 'Rp 350.000',
    image: '/images/brio.png',
    features: ['Compact', 'Fuel Efficient', 'Easy Park'],
    featured: true
  },
  {
    id: 'civic',
    name: 'Honda Civic',
    type: 'Luxury, Sporty',
    capacity: '5 Kursi',
    transmission: 'Automatic',
    lepasKunci: true,
    price: 'Rp 1.500.000',
    image: '/images/HONDA CIVIC.png',
    features: ['Turbo', 'Sport Mode', 'Premium Audio'],
    featured: true
  },
  {
    id: 'innova-reborn',
    name: 'Toyota Innova Reborn',
    type: 'Powerful, Spacious',
    capacity: '7 Kursi',
    transmission: 'Automatic/Manual',
    lepasKunci: true,
    price: 'Rp 800.000',
    image: '/images/innova-reborn.jpeg',
    features: ['Diesel', 'Captain Seat', 'Spacious'],
    featured: true
  },
  {
    id: 'alphard-new',
    name: 'Toyota Alphard New',
    type: 'VIP, Luxury',
    capacity: '7 Kursi',
    transmission: 'Automatic',
    lepasKunci: false,
    price: 'Rp 3.500.000',
    image: '/images/ALPHARD NEW.png',
    features: ['Pilot Seat', 'Sunroof', 'Premium Luxury'],
    featured: true
  },
  {
    id: 'fortuner-gr',
    name: 'Toyota Fortuner GR',
    type: 'Sporty, High-end',
    capacity: '7 Kursi',
    transmission: 'Automatic',
    lepasKunci: true,
    price: 'Rp 1.200.000',
    image: '/images/fortuner.jpeg',
    features: ['Diesel', 'Turbo', 'Leather Seats'],
    featured: false
  },
  {
    id: 'avanza',
    name: 'Toyota Avanza',
    type: 'Family, Reliable',
    capacity: '7 Kursi',
    transmission: 'Automatic',
    lepasKunci: true,
    price: 'Rp 500.000',
    image: '/images/avanza.jpeg',
    features: ['Safety Sense', 'Efficient', 'Modern'],
    featured: false
  },
  {
    id: 'ayla-new',
    name: 'Daihatsu Ayla New',
    type: 'Compact, Economical',
    capacity: '5 Kursi',
    transmission: 'Automatic/Manual',
    lepasKunci: true,
    price: 'Rp 300.000',
    image: '/images/AYLA NEW.png',
    features: ['Efficient', 'Easy to Drive'],
    featured: false
  },
  {
    id: 'hiace-premio',
    name: 'Toyota Hiace Premio',
    type: 'Large Group, Travel',
    capacity: '14 Kursi',
    transmission: 'Manual',
    lepasKunci: false,
    price: 'Rp 1.500.000',
    image: '/images/HIACE PREMIO.png',
    features: ['Spacious', 'AC Central', 'Group Travel'],
    featured: false
  },
  {
    id: 'honda-jazz',
    name: 'Honda Jazz',
    type: 'Sporty, Compact',
    capacity: '5 Kursi',
    transmission: 'Automatic/Manual',
    lepasKunci: true,
    price: 'Rp 450.000',
    image: '/images/HONDA JAZZ.png',
    features: ['Sporty', 'Easy Park'],
    featured: false
  },
  {
    id: 'hrv',
    name: 'Honda HRV',
    type: 'Stylish, Crossover',
    capacity: '5 Kursi',
    transmission: 'Automatic',
    lepasKunci: true,
    price: 'Rp 800.000',
    image: '/images/HRV.png',
    features: ['Stylish', 'Panoramic'],
    featured: false
  },
  {
    id: 'ertiga',
    name: 'Suzuki Ertiga',
    type: 'Family, Comfort',
    capacity: '7 Kursi',
    transmission: 'Automatic/Manual',
    lepasKunci: true,
    price: 'Rp 500.000',
    image: '/images/SUZUKI ERTIGA.png',
    features: ['Comfort', 'Efficient'],
    featured: false
  },
  {
    id: 'terios-new',
    name: 'Daihatsu Terios New',
    type: 'SUV, Adventure',
    capacity: '7 Kursi',
    transmission: 'Automatic/Manual',
    lepasKunci: true,
    price: 'Rp 600.000',
    image: '/images/TERIOS NEW.png',
    features: ['SUV', 'Adventure Ready'],
    featured: false
  },
  {
    id: 'agya',
    name: 'Toyota Agya',
    type: 'Compact, City Car',
    capacity: '5 Kursi',
    transmission: 'Automatic/Manual',
    lepasKunci: true,
    price: 'Rp 300.000',
    image: '/images/TOYOTA AGYA.png',
    features: ['City Car', 'Efficient'],
    featured: false
  },
  {
    id: 'rush',
    name: 'Toyota Rush',
    type: 'SUV, Reliable',
    capacity: '7 Kursi',
    transmission: 'Automatic/Manual',
    lepasKunci: true,
    price: 'Rp 600.000',
    image: '/images/TOYOTA RUSH.png',
    features: ['Reliable', 'SUV'],
    featured: false
  },
  {
    id: 'xenia',
    name: 'Daihatsu Xenia',
    type: 'Family, Practical',
    capacity: '7 Kursi',
    transmission: 'Automatic/Manual',
    lepasKunci: true,
    price: 'Rp 500.000',
    image: '/images/XENIA.png',
    features: ['Practical', 'Reliable'],
    featured: false
  }
];
